name: flutter_sample2
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  ext_storage:
    git:
      url: git://github.com/lavahasif/ext_storage_ups.git
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  ftpconnect: ^1.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod:
  intl: 0.17.0
  path_provider: 2.0.2
  permission_handler: ^8.1.6
  wifi_info_flutter: ^2.0.2
  flutter_mailer: ^2.0.0
  flutter_archive: ^4.1.0
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator: ^1.1.1
  pedantic_mono:
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

